# Generated by Django 4.2 on 2024-09-30 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('level', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('request_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1000, null=True)),
                ('method', models.CharField(blank=True, max_length=1000, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('request_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('error_source', models.CharField(blank=True, choices=[('Front-End', 'Front-End'), ('Back-End', 'Back-End')], max_length=10, null=True)),
                ('error_type', models.CharField(blank=True, choices=[('Error', 'Error'), ('Debug', 'Debug')], max_length=10, null=True)),
                ('query_parameters', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
            },
        ),
    ]
